### ISSUE TITLE
Will version 0.2.3 of javabrake compile under java 8?

### ISSUE THREAD

**Issue by landydan** [airbrake/javabrake#59]
Hello,

I just tried upgrading to the latest version of javabrake (0.2.3) and am encountering the error below.
I did some googling and discovered that the problem is because the code was compiled with Java 11, but we are still using Java 8.
Can I obtain a version of Airbrake that was compiled with Java 8?

If not, we could pull your code and compile our own WAR, provided that the code does not depend on Java 11.  Do you know the answer to that?

Thanks.

**Comment by nthatcher-airbrake** [comment]
You are able to clone the repo and build it in a version that works for you. NOTE: There is the risk that java 8 has something which is superseded in Java 11. 
Unfortunately, we (currently) don’t publish versions of our package built with diff versions of the JDK

**Comment by mmcdaris** [comment]
@landydan thanks for reporting this. Can you please try `v0.2.4`? It was built with Java 8 so I suspect that will solve the issue for you. Please let us know how it goes. 👍

**Comment by landydan** [comment]
Thank you for you help.

It appears that version 0.2.4 is working.  I'll just need to do a bit more testing.

One thing:  When I ran our app initially with the wrong Airbrake credentials, I saw a GSON error in the logs at startup time.

It looks like the bad credentials caused an "Access Denied" message in XML format, but the code is trying to parse this as json? 

Here's the error:

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:176)
at com.google.gson.Gson.fromJson(Gson.java:803)
at com.google.gson.Gson.fromJson(Gson.java:768)
at com.google.gson.Gson.fromJson(Gson.java:717)
at com.google.gson.Gson.fromJson(Gson.java:689)
at io.airbrake.javabrake.PollTask.run(PollTask.java:69)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)
Caused by: java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1
at com.google.gson.stream.JsonReader.beginObject(JsonReader.java:374)
at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
... 7 more
parse error on: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>1HNCWW7DWFTG2SQ3</RequestId><HostId>tzUk2bf8OAHNDvbo9nTNxeyJMsI8TZe7nRazVX9vSM3hTTJUhUJWchO2gsj5XmTjhLhoYwUUfHM=</HostId></Error>
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 1

**Comment by nthatcher-airbrake** [comment]
Tagging @mmcdaris In case you missed the above response from Dan

**Comment by nthatcher-airbrake** [comment]
@scottsbaldwin see above

**Comment by landydan** [comment]
Correct -- the issue reported here is not a problem for me, I was only passing it on for your information.

Thanks for your help.

**Comment by sumitjoshi1989** [comment]
Access Denied issue is handled
